"""Candidates tool specifications.

Generated from the pre-refactor hand-written toolsets, then reviewed. Edit this
file directly; it is the source of truth for these tools.
"""

from __future__ import annotations

from typing import Any  # noqa: F401  (used in parameter annotations)

from cats_mcp.registry.models import (
    Param,
    ParamLocation,
    ResponseStrategy,
    Safety,
    ToolSpec,
    Transform,  # noqa: F401  (used by some specs)
)

SPECS: list[ToolSpec] = [
    ToolSpec(
        name="list_candidates",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates",
        description="List candidates with pagination (returns SUMMARY by default). Use get_candidate(id) for full details of a specific candidate. Use this to enumerate candidates and obtain their ids.\n\nWraps: GET /candidates",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="candidates",
        toolset="candidates",
        params=(
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 10, max: 100)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number to retrieve (default: 1)",
                location=ParamLocation.QUERY,
                default=1,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include (default: id,first_name,last_name,email,status,created_date).\n    Set to "all" for full API response.',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="get_candidate",
        resource="candidate",
        operation="get",
        method="GET",
        endpoint="/candidates/{candidate_id}",
        description="Retrieve one candidate's full profile by id. Use this after a search or list has given you an id and you need complete detail on that specific person.\n\nWraps: GET /candidates/{candidate_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="create_candidate",
        resource="candidate",
        operation="create",
        method="POST",
        endpoint="/candidates",
        description="Create a new candidate in the system. Use this to add a new candidate record.\n\nWraps: POST /candidates",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="first_name",
                annotation=str,
                description="Candidate's first name",
                location=ParamLocation.BODY,
            ),
            Param(
                name="last_name",
                annotation=str,
                description="Candidate's last name",
                location=ParamLocation.BODY,
            ),
            Param(
                name="email",
                annotation=str,
                description="Email address",
                location=ParamLocation.BODY,
            ),
            Param(
                name="phone",
                annotation=str | None,
                description="Phone number (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="resume_url",
                annotation=str | None,
                description="URL to resume document (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="linkedin_url",
                annotation=str | None,
                description="LinkedIn profile URL (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="update_candidate",
        resource="candidate",
        operation="update",
        method="PUT",
        endpoint="/candidates/{candidate_id}",
        description="Update an existing candidate's information. Use this to change fields on an existing candidate. Only the fields you supply are modified.\n\nWraps: PUT /candidates/{candidate_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="first_name",
                annotation=str | None,
                description="Updated first name (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="last_name",
                annotation=str | None,
                description="Updated last name (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="email",
                annotation=str | None,
                description="Updated email address (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="phone",
                annotation=str | None,
                description="Updated phone number (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="delete_candidate",
        resource="candidate",
        operation="delete",
        method="DELETE",
        endpoint="/candidates/{candidate_id}",
        description="Permanently delete a candidate and their associated records from CATS. This cannot be undone. Use only on explicit instruction to remove a person's record.\n\nWraps: DELETE /candidates/{candidate_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="search_candidates",
        resource="candidate",
        operation="search",
        method="GET",
        endpoint="/candidates/search",
        description="Find candidates by free-text keyword across their profile - name, email, job title, skills, location, city or region. Use this for open-ended people searches such as finding welders in Kamloops or electricians near a mine site. Returns compact summaries with ids; fetch details separately.\n\nWraps: GET /candidates/search",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="candidates",
        toolset="candidates",
        params=(
            Param(
                name="query",
                annotation=str,
                description="Search query string",
                location=ParamLocation.QUERY,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 10)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include, or "all" for full response',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="filter_candidates",
        resource="candidate",
        operation="filter",
        method="POST",
        endpoint="/candidates/search",
        description="Find candidates by exact structured criteria - status, custom field values, hot flag, dates, or geographic distance from a postal code. Use this when you know the precise field and value to match, rather than searching by keyword. Supports combining conditions with AND/OR.\n\nWraps: POST /candidates/search",
        safety=Safety.WRITE,
        response=ResponseStrategy.SUMMARY,
        collection_key="candidates",
        toolset="candidates",
        params=(
            Param(
                name="filter_field",
                annotation=str,
                description='Field to filter on (e.g., "status_id", "is_hot")',
                location=ParamLocation.BODY,
                wire_name="field",
            ),
            Param(
                name="filter_type",
                annotation=str,
                description='Filter operator ("contains", "exactly", "is_empty", "greater_than", "less_than", "between")',
                location=ParamLocation.BODY,
                wire_name="filter",
            ),
            Param(
                name="filter_value",
                annotation=Any,
                description="Value to filter by",
                location=ParamLocation.BODY,
                wire_name="value",
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 10)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number to retrieve (default: 1)",
                location=ParamLocation.QUERY,
                default=1,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include, or "all" for full response',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="authorize_candidate",
        resource="candidate",
        operation="authorize",
        method="POST",
        endpoint="/candidates/authorization",
        description="Authorize a candidate action (e.g., portal access).\n\nWraps: POST /candidates/authorization",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.BODY,
            ),
            Param(
                name="action",
                annotation=str,
                description="The authorization action to perform",
                location=ParamLocation.BODY,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_pipelines",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/{candidate_id}/pipelines",
        description="List every job a candidate has been submitted to, with their current status in each. Use this to see what a candidate is currently being considered for, whether they were already submitted to a role, or where they are in a hiring process.\n\nWraps: GET /candidates/{candidate_id}/pipelines",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="pipelines",
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_activities",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/{candidate_id}/activities",
        description="Retrieve a candidate's recruiting and communication activity history, including calls, email records, text-message records, meetings, interviews, notes and follow-ups. Use this to determine when a candidate was last contacted, what the outcome of prior outreach was, whether anyone has already reached out, or whether a candidate is due for re-engagement or follow-up.\n\nWraps: GET /candidates/{candidate_id}/activities",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="activities",
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
        ),
    ),
    ToolSpec(
        name="create_candidate_activity",
        resource="candidate",
        operation="create",
        method="POST",
        endpoint="/candidates/{candidate_id}/activities",
        description="Record an activity against a candidate - log that a call, email, text message, meeting or interview took place, or attach a note. Use this after contacting a candidate through any external channel so the outreach history stays accurate. This records that something happened; it does not send anything.\n\nWraps: POST /candidates/{candidate_id}/activities",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="activity_type",
                annotation=str,
                description="Type of activity (e.g., 'meeting_scheduled', 'email_sent')",
                location=ParamLocation.BODY,
                wire_name="type",
            ),
            Param(
                name="description",
                annotation=str,
                description="Description of the activity",
                location=ParamLocation.BODY,
            ),
            Param(
                name="date",
                annotation=str | None,
                description="Activity date in ISO format (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_attachments",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/{candidate_id}/attachments",
        description="List the files attached to a candidate - resumes, cover letters, certificates and tickets - as metadata only. Use this to discover what documents exist before downloading one. Does not return file contents.\n\nWraps: GET /candidates/{candidate_id}/attachments",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="attachments",
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
        ),
    ),
    ToolSpec(
        name="upload_candidate_attachment",
        resource="candidate",
        operation="upload",
        method="POST",
        endpoint="/candidates/{candidate_id}/attachments",
        description="Upload an attachment for a candidate. Use this to attach a file to the record.\n\nWraps: POST /candidates/{candidate_id}/attachments",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="file_name",
                annotation=str,
                description="Name of the file",
                location=ParamLocation.BODY,
            ),
            Param(
                name="file_type",
                annotation=str,
                description="Type of file (e.g., 'resume', 'cover_letter')",
                location=ParamLocation.BODY,
            ),
            Param(
                name="file_url",
                annotation=str,
                description="URL to the file to upload",
                location=ParamLocation.BODY,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_custom_fields",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/{candidate_id}/custom_fields",
        description="Retrieve the values of a candidate's custom fields - the account-specific data such as certifications, trade qualifications, availability or screening answers. Use this to read information not held in standard candidate fields.\n\nWraps: GET /candidates/{candidate_id}/custom_fields",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="custom_fields",
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="get_candidate_custom_field",
        resource="candidate",
        operation="get",
        method="GET",
        endpoint="/candidates/{candidate_id}/custom_fields/{field_id}",
        description="Get a specific custom field for a candidate. Use this when you already have a candidate id and need its detail.\n\nWraps: GET /candidates/{candidate_id}/custom_fields/{field_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="field_id",
                annotation=int | str,
                description="The unique identifier of the custom field",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="update_candidate_custom_field",
        resource="candidate",
        operation="update",
        method="PUT",
        endpoint="/candidates/{candidate_id}/custom_fields/{field_id}",
        description="Update a specific custom field for a candidate. Use this to change fields on an existing candidate. Only the fields you supply are modified.\n\nWraps: PUT /candidates/{candidate_id}/custom_fields/{field_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="field_id",
                annotation=int | str,
                description="The unique identifier of the custom field",
                location=ParamLocation.PATH,
            ),
            Param(
                name="value",
                annotation=Any,
                description="The new value for the custom field",
                location=ParamLocation.BODY,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_emails",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/{candidate_id}/emails",
        description="List all email addresses for a candidate. Use this to enumerate candidates and obtain their ids.\n\nWraps: GET /candidates/{candidate_id}/emails",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="emails",
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
        ),
    ),
    ToolSpec(
        name="create_candidate_email",
        resource="candidate",
        operation="create",
        method="POST",
        endpoint="/candidates/{candidate_id}/emails",
        description="Add a new email address for a candidate. Use this to add a new candidate record.\n\nWraps: POST /candidates/{candidate_id}/emails",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="email",
                annotation=str,
                description="Email address to add",
                location=ParamLocation.BODY,
            ),
            Param(
                name="email_type",
                annotation=str,
                description="Type of email (e.g., 'personal', 'work') (default: 'personal')",
                location=ParamLocation.BODY,
                default="personal",
                wire_name="type",
            ),
        ),
    ),
    ToolSpec(
        name="update_candidate_email",
        resource="candidate",
        operation="update",
        method="PUT",
        endpoint="/candidates/{candidate_id}/emails/{email_id}",
        description="Update a candidate's email address. Use this to change fields on an existing candidate. Only the fields you supply are modified.\n\nWraps: PUT /candidates/{candidate_id}/emails/{email_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="email_id",
                annotation=int | str,
                description="The unique identifier of the email",
                location=ParamLocation.PATH,
            ),
            Param(
                name="email",
                annotation=str,
                description="Updated email address",
                location=ParamLocation.BODY,
            ),
            Param(
                name="email_type",
                annotation=str | None,
                description="Updated email type (optional)",
                location=ParamLocation.BODY,
                default=None,
                wire_name="type",
            ),
        ),
    ),
    ToolSpec(
        name="delete_candidate_email",
        resource="candidate",
        operation="delete",
        method="DELETE",
        endpoint="/candidates/{candidate_id}/emails/{email_id}",
        description="Delete a candidate's email address. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /candidates/{candidate_id}/emails/{email_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="email_id",
                annotation=int | str,
                description="The unique identifier of the email to delete",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_phones",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/{candidate_id}/phones",
        description="List all phone numbers for a candidate. Use this to enumerate candidates and obtain their ids.\n\nWraps: GET /candidates/{candidate_id}/phones",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="phones",
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
        ),
    ),
    ToolSpec(
        name="create_candidate_phone",
        resource="candidate",
        operation="create",
        method="POST",
        endpoint="/candidates/{candidate_id}/phones",
        description="Add a new phone number for a candidate. Use this to add a new candidate record.\n\nWraps: POST /candidates/{candidate_id}/phones",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone",
                annotation=str,
                description="Phone number to add",
                location=ParamLocation.BODY,
            ),
            Param(
                name="phone_type",
                annotation=str,
                description="Type of phone (e.g., 'mobile', 'home', 'work') (default: 'mobile')",
                location=ParamLocation.BODY,
                default="mobile",
                wire_name="type",
            ),
        ),
    ),
    ToolSpec(
        name="update_candidate_phone",
        resource="candidate",
        operation="update",
        method="PUT",
        endpoint="/candidates/{candidate_id}/phones/{phone_id}",
        description="Update a candidate's phone number. Use this to change fields on an existing candidate. Only the fields you supply are modified.\n\nWraps: PUT /candidates/{candidate_id}/phones/{phone_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone_id",
                annotation=int | str,
                description="The unique identifier of the phone",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone",
                annotation=str,
                description="Updated phone number",
                location=ParamLocation.BODY,
            ),
            Param(
                name="phone_type",
                annotation=str | None,
                description="Updated phone type (optional)",
                location=ParamLocation.BODY,
                default=None,
                wire_name="type",
            ),
        ),
    ),
    ToolSpec(
        name="delete_candidate_phone",
        resource="candidate",
        operation="delete",
        method="DELETE",
        endpoint="/candidates/{candidate_id}/phones/{phone_id}",
        description="Delete a candidate's phone number. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /candidates/{candidate_id}/phones/{phone_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone_id",
                annotation=int | str,
                description="The unique identifier of the phone to delete",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_tags",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/{candidate_id}/tags",
        description="List the tags applied to a candidate. Tags are how candidates are grouped by trade, certification, source or campaign. Use this to see how a candidate is categorised.\n\nWraps: GET /candidates/{candidate_id}/tags",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="tags",
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="replace_candidate_tags",
        resource="candidate",
        operation="replace",
        method="POST",
        endpoint="/candidates/{candidate_id}/tags",
        description="Replace all of a candidate's tags with a new set. This removes any tag not in the list. Prefer attach_candidate_tags unless deliberately resetting categorisation.\n\nWraps: POST /candidates/{candidate_id}/tags",
        safety=Safety.BULK,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_ids",
                annotation=list[int],
                description="List of tag IDs to assign",
                location=ParamLocation.BODY,
                wire_name="tags",
                transform=Transform.WRAP_ID,
            ),
        ),
    ),
    ToolSpec(
        name="attach_candidate_tags",
        resource="candidate",
        operation="attach",
        method="PUT",
        endpoint="/candidates/{candidate_id}/tags",
        description="Add tags to a candidate while keeping their existing tags. Use this to categorise a candidate by trade, certification, source or campaign without disturbing tags already applied.\n\nWraps: PUT /candidates/{candidate_id}/tags",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_ids",
                annotation=list[int],
                description="List of tag IDs to add",
                location=ParamLocation.BODY,
                wire_name="tags",
                transform=Transform.WRAP_ID,
            ),
        ),
    ),
    ToolSpec(
        name="delete_candidate_tag",
        resource="candidate",
        operation="delete",
        method="DELETE",
        endpoint="/candidates/{candidate_id}/tags/{tag_id}",
        description="Remove a specific tag from a candidate. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /candidates/{candidate_id}/tags/{tag_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_id",
                annotation=int | str,
                description="The unique identifier of the tag to remove",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_work_history",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/{candidate_id}/work_history",
        description="Retrieve a candidate's employment history: previous employers, job titles and dates. Use this to assess experience, check who they currently work for, or verify time in a trade.\n\nWraps: GET /candidates/{candidate_id}/work_history",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="work_history",
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
        ),
    ),
    ToolSpec(
        name="create_candidate_work_history",
        resource="candidate",
        operation="create",
        method="POST",
        endpoint="/candidates/{candidate_id}/work_history",
        description="Add a work history entry for a candidate. Use this to add a new candidate record.\n\nWraps: POST /candidates/{candidate_id}/work_history",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="company",
                annotation=str,
                description="Company name",
                location=ParamLocation.BODY,
            ),
            Param(
                name="title",
                annotation=str,
                description="Job title",
                location=ParamLocation.BODY,
            ),
            Param(
                name="start_date",
                annotation=str,
                description="Start date in ISO format (YYYY-MM-DD)",
                location=ParamLocation.BODY,
            ),
            Param(
                name="end_date",
                annotation=str | None,
                description="End date in ISO format (optional, null for current)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="description",
                annotation=str | None,
                description="Job description (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="get_candidate_work_history_item",
        resource="candidate",
        operation="get",
        method="GET",
        endpoint="/candidates/{candidate_id}/work_history/{work_history_id}",
        description="Get a specific work history item for a candidate. Use this when you already have a candidate id and need its detail.\n\nWraps: GET /candidates/{candidate_id}/work_history/{work_history_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="work_history_id",
                annotation=int | str,
                description="The unique identifier of the work history item",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="update_candidate_work_history_item",
        resource="candidate",
        operation="update",
        method="PUT",
        endpoint="/candidates/{candidate_id}/work_history/{work_history_id}",
        description="Update a work history item for a candidate. Use this to change fields on an existing candidate. Only the fields you supply are modified.\n\nWraps: PUT /candidates/{candidate_id}/work_history/{work_history_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="work_history_id",
                annotation=int | str,
                description="The unique identifier of the work history item",
                location=ParamLocation.PATH,
            ),
            Param(
                name="company",
                annotation=str | None,
                description="Updated company name (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="title",
                annotation=str | None,
                description="Updated job title (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="start_date",
                annotation=str | None,
                description="Updated start date (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="end_date",
                annotation=str | None,
                description="Updated end date (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="description",
                annotation=str | None,
                description="Updated description (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="delete_candidate_work_history_item",
        resource="candidate",
        operation="delete",
        method="DELETE",
        endpoint="/candidates/{candidate_id}/work_history/{work_history_id}",
        description="Delete a work history item for a candidate. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /candidates/{candidate_id}/work_history/{work_history_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="work_history_id",
                annotation=int | str,
                description="The unique identifier of the work history item",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_lists",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/lists",
        description="List the saved candidate lists in the account. Lists are static groupings of candidates, useful as shortlists or campaign audiences.\n\nWraps: GET /candidates/lists",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="lists",
        toolset="candidates",
        params=(
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number (default: 1)",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="get_candidate_list",
        resource="candidate",
        operation="get",
        method="GET",
        endpoint="/candidates/lists/{list_id}",
        description="Get a specific candidate list. Use this when you already have a candidate id and need its detail.\n\nWraps: GET /candidates/lists/{list_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="candidates",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="create_candidate_list",
        resource="candidate",
        operation="create",
        method="POST",
        endpoint="/candidates/lists",
        description="Create a new candidate list. Use this to add a new candidate record.\n\nWraps: POST /candidates/lists",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="name",
                annotation=str,
                description="Name of the list",
                location=ParamLocation.BODY,
            ),
            Param(
                name="description",
                annotation=str | None,
                description="Description of the list (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="delete_candidate_list",
        resource="candidate",
        operation="delete",
        method="DELETE",
        endpoint="/candidates/lists/{list_id}",
        description="Delete a candidate list. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /candidates/lists/{list_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_list_items",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/lists/{list_id}/items",
        description="List all items in a candidate list. Use this to enumerate candidates and obtain their ids.\n\nWraps: GET /candidates/lists/{list_id}/items",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="items",
        toolset="candidates",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number (default: 1)",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="get_candidate_list_item",
        resource="candidate",
        operation="get",
        method="GET",
        endpoint="/candidates/lists/{list_id}/items/{item_id}",
        description="Get a specific candidate list item. Use this when you already have a candidate id and need its detail.\n\nWraps: GET /candidates/lists/{list_id}/items/{item_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="candidates",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
            Param(
                name="item_id",
                annotation=int | str,
                description="The unique identifier of the list item",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="create_candidate_list_items",
        resource="candidate",
        operation="create",
        method="POST",
        endpoint="/candidates/lists/{list_id}/items",
        description="Add candidates to a list. Use this to add a new candidate record.\n\nWraps: POST /candidates/lists/{list_id}/items",
        safety=Safety.BULK,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
            Param(
                name="candidate_ids",
                annotation=list[int],
                description="List of candidate IDs to add",
                location=ParamLocation.BODY,
                wire_name="items",
                transform=Transform.WRAP_CANDIDATE_ID,
            ),
        ),
    ),
    ToolSpec(
        name="delete_candidate_list_item",
        resource="candidate",
        operation="delete",
        method="DELETE",
        endpoint="/candidates/lists/{list_id}/items/{item_id}",
        description="Remove a candidate from a list. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /candidates/lists/{list_id}/items/{item_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
            Param(
                name="item_id",
                annotation=int | str,
                description="The unique identifier of the list item",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="get_candidate_thumbnail",
        resource="candidate",
        operation="get",
        method="GET",
        endpoint="/candidates/{candidate_id}/thumbnail",
        description="Get a candidate's thumbnail image. Use this when you already have a candidate id and need its detail.\n\nWraps: GET /candidates/{candidate_id}/thumbnail",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="change_candidate_thumbnail",
        resource="candidate",
        operation="change",
        method="PUT",
        endpoint="/candidates/{candidate_id}/thumbnail",
        description="Update a candidate's thumbnail image.\n\nWraps: PUT /candidates/{candidate_id}/thumbnail",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="image_data",
                annotation=str,
                description="Base64 encoded image data or image URL",
                location=ParamLocation.BODY,
                wire_name="image",
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_applications",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/{candidate_id}/applications",
        description=(
            "List the job applications a candidate has submitted, across every job. Use "
            "this to see what a candidate has applied for, check whether they already "
            "applied to a role before submitting them again, or review their application "
            "history with this organisation.\n\nWraps: GET /candidates/{candidate_id}/applications"
        ),
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="applications",
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 10, max: 100)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number to retrieve (default: 1)",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_tasks",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/{candidate_id}/tasks",
        description=(
            "List the tasks and reminders attached to a candidate. Use this to see "
            "outstanding follow-ups, who owns them and when they are due.\n\n"
            "Wraps: GET /candidates/{candidate_id}/tasks"
        ),
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="tasks",
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_candidate_custom_field_definitions",
        resource="candidate",
        operation="list",
        method="GET",
        endpoint="/candidates/custom_fields",
        description=(
            "List every candidate custom field configured on this CATS account, with its "
            "id, label and type. Custom fields hold account-specific data such as trade "
            "certifications, availability or screening answers. Call this first to "
            "discover which fields exist and their ids, because the tools that read or "
            "write a value require the field id and those ids differ per account.\n\n"
            "Wraps: GET /candidates/custom_fields"
        ),
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="custom_fields",
        toolset="candidates",
        params=(),
    ),
    ToolSpec(
        name="get_candidate_custom_field_definition",
        resource="candidate",
        operation="get",
        method="GET",
        endpoint="/candidates/custom_fields/{field_id}",
        description=(
            "Retrieve the definition of one candidate custom field, including its type and "
            "any selectable options. Use this to find the valid values for a dropdown or "
            "checkbox field before writing to it.\n\n"
            "Wraps: GET /candidates/custom_fields/{field_id}"
        ),
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="candidates",
        params=(
            Param(
                name="field_id",
                annotation=int | str,
                description="The unique identifier of the custom field definition",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="get_candidate_email",
        resource="candidate",
        operation="get",
        method="GET",
        endpoint="/candidates/{candidate_id}/emails/{email_id}",
        description=(
            "Retrieve one specific email address record for a candidate. Use this when you "
            "have an email id and need its detail; use list_candidate_emails to find "
            "ids.\n\nWraps: GET /candidates/{candidate_id}/emails/{email_id}"
        ),
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="email_id",
                annotation=int | str,
                description="The unique identifier of the email record",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="get_candidate_phone",
        resource="candidate",
        operation="get",
        method="GET",
        endpoint="/candidates/{candidate_id}/phones/{phone_id}",
        description=(
            "Retrieve one specific phone number record for a candidate. Use this when you "
            "have a phone id and need its detail; use list_candidate_phones to find "
            "ids.\n\nWraps: GET /candidates/{candidate_id}/phones/{phone_id}"
        ),
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="candidates",
        params=(
            Param(
                name="candidate_id",
                annotation=int | str,
                description="The unique identifier of the candidate",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone_id",
                annotation=int | str,
                description="The unique identifier of the phone record",
                location=ParamLocation.PATH,
            ),
        ),
    ),
]
