"""Companies tool specifications.

Generated from the pre-refactor hand-written toolsets, then reviewed. Edit this
file directly; it is the source of truth for these tools.
"""

from __future__ import annotations

from typing import Any  # noqa: F401  (used in parameter annotations)

from cats_mcp.registry.models import (
    Param,
    ParamLocation,
    ResponseStrategy,
    Safety,
    ToolSpec,
    Transform,  # noqa: F401  (used by some specs)
)

SPECS: list[ToolSpec] = [
    ToolSpec(
        name="list_companies",
        resource="company",
        operation="list",
        method="GET",
        endpoint="/companies",
        description="List companies with pagination (returns SUMMARY by default). Use get_company(id) for full details of a specific company. Use this to enumerate companies and obtain their ids.\n\nWraps: GET /companies",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="companies",
        toolset="companies",
        params=(
            Param(
                name="per_page",
                annotation=int,
                description="Number of companies per page (default: 10, max: 100)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number for pagination (default: 1)",
                location=ParamLocation.QUERY,
                default=1,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include, or "all" for full response',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="get_company",
        resource="company",
        operation="get",
        method="GET",
        endpoint="/companies/{company_id}",
        description="Get detailed information about a specific company. Use this when you already have a company id and need its detail.\n\nWraps: GET /companies/{company_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Unique identifier for the company",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="create_company",
        resource="company",
        operation="create",
        method="POST",
        endpoint="/companies",
        description="Create a new company record. Use this to add a new company record.\n\nWraps: POST /companies",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="name",
                annotation=str,
                description="Company name (required)",
                location=ParamLocation.BODY,
            ),
            Param(
                name="website",
                annotation=str | None,
                description="Company website URL",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="phone",
                annotation=str | None,
                description="Company phone number",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="address",
                annotation=str | None,
                description="Street address",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="city",
                annotation=str | None,
                description="City",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="state",
                annotation=str | None,
                description="State/province",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="zip_code",
                annotation=str | None,
                description="ZIP or postal code",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="notes",
                annotation=str | None,
                description="Additional notes about the company",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="update_company",
        resource="company",
        operation="update",
        method="PUT",
        endpoint="/companies/{company_id}",
        description="Update an existing company record. Use this to change fields on an existing company. Only the fields you supply are modified.\n\nWraps: PUT /companies/{company_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="ID of company to update",
                location=ParamLocation.PATH,
            ),
            Param(
                name="name",
                annotation=str | None,
                description="Updated company name",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="website",
                annotation=str | None,
                description="Updated website URL",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="phone",
                annotation=str | None,
                description="Updated phone number",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="address",
                annotation=str | None,
                description="Updated street address",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="city",
                annotation=str | None,
                description="Updated city",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="state",
                annotation=str | None,
                description="Updated state/province",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="zip_code",
                annotation=str | None,
                description="Updated ZIP/postal code",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="notes",
                annotation=str | None,
                description="Updated notes",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="delete_company",
        resource="company",
        operation="delete",
        method="DELETE",
        endpoint="/companies/{company_id}",
        description="Delete a company record (permanent). Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /companies/{company_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="ID of company to delete",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="search_companies",
        resource="company",
        operation="search",
        method="GET",
        endpoint="/companies/search",
        description="Search companies by name or other criteria (returns SUMMARY by default). Use get_company(id) for full details. Use this for keyword searches across companies.\n\nWraps: GET /companies/search",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="companies",
        toolset="companies",
        params=(
            Param(
                name="query",
                annotation=str,
                description="Search query string",
                location=ParamLocation.QUERY,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 10)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include, or "all" for full response',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="filter_companies",
        resource="company",
        operation="filter",
        method="POST",
        endpoint="/companies/search",
        description="Filter companies using advanced criteria (returns SUMMARY by default). Use get_company(id) for full details. Use this to match companies on exact field values.\n\nWraps: POST /companies/search",
        safety=Safety.WRITE,
        response=ResponseStrategy.SUMMARY,
        collection_key="companies",
        toolset="companies",
        params=(
            Param(
                name="filter_field",
                annotation=str,
                description='Field to filter on (e.g., "city", "state", "name")',
                location=ParamLocation.BODY,
                wire_name="field",
            ),
            Param(
                name="filter_type",
                annotation=str,
                description='Filter operator ("contains", "exactly", "is_empty", "greater_than", "less_than", "between")',
                location=ParamLocation.BODY,
                wire_name="filter",
            ),
            Param(
                name="filter_value",
                annotation=Any,
                description="Value to filter by",
                location=ParamLocation.BODY,
                wire_name="value",
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Results per page (default: 10)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number",
                location=ParamLocation.QUERY,
                default=1,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include, or "all" for full response',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="list_company_activities",
        resource="company",
        operation="list",
        method="GET",
        endpoint="/companies/{company_id}/activities",
        description="List all activities for a specific company. Use this to enumerate companies and obtain their ids.\n\nWraps: GET /companies/{company_id}/activities",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="activities",
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Results per page",
                location=ParamLocation.QUERY,
                default=25,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="create_company_activity",
        resource="company",
        operation="create",
        method="POST",
        endpoint="/companies/{company_id}/activities",
        description="Create an activity for a company. Use this to add a new company record.\n\nWraps: POST /companies/{company_id}/activities",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="activity_type",
                annotation=str,
                description="Type (email, meeting, call_talked, call_lvm, call_missed, text_message, other)",
                location=ParamLocation.BODY,
                wire_name="type",
            ),
            Param(
                name="description",
                annotation=str,
                description="Activity description",
                location=ParamLocation.BODY,
            ),
            Param(
                name="notes",
                annotation=str | None,
                description="Additional notes",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="list_company_attachments",
        resource="company",
        operation="list",
        method="GET",
        endpoint="/companies/{company_id}/attachments",
        description="List all attachments for a company. Use this to enumerate companies and obtain their ids.\n\nWraps: GET /companies/{company_id}/attachments",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="attachments",
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Results per page",
                location=ParamLocation.QUERY,
                default=25,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="upload_company_attachment",
        resource="company",
        operation="upload",
        method="POST",
        endpoint="/companies/{company_id}/attachments",
        description="Upload an attachment to a company. Use this to attach a file to the record.\n\nWraps: POST /companies/{company_id}/attachments",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="file_data",
                annotation=dict[str, Any],
                description="File upload data (multipart/form-data)",
                location=ParamLocation.BODY,
                transform=Transform.SPREAD,
            ),
        ),
    ),
    ToolSpec(
        name="list_company_contacts",
        resource="company",
        operation="list",
        method="GET",
        endpoint="/companies/{company_id}/contacts",
        description="List all contacts associated with a company. Use this to enumerate companies and obtain their ids.\n\nWraps: GET /companies/{company_id}/contacts",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="contacts",
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Results per page",
                location=ParamLocation.QUERY,
                default=25,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="get_company_custom_fields",
        resource="company",
        operation="get",
        method="GET",
        endpoint="/companies/{company_id}/custom_fields",
        description="Get custom fields for a company. Use this when you already have a company id and need its detail.\n\nWraps: GET /companies/{company_id}/custom_fields",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_company_departments",
        resource="company",
        operation="list",
        method="GET",
        endpoint="/companies/{company_id}/departments",
        description="List all departments within a company. Use this to enumerate companies and obtain their ids.\n\nWraps: GET /companies/{company_id}/departments",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="departments",
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="create_company_department",
        resource="company",
        operation="create",
        method="POST",
        endpoint="/companies/{company_id}/departments",
        description="Create a new department for a company. Use this to add a new company record.\n\nWraps: POST /companies/{company_id}/departments",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="name",
                annotation=str,
                description="Department name",
                location=ParamLocation.BODY,
            ),
            Param(
                name="description",
                annotation=str | None,
                description="Department description",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="update_company_department",
        resource="company",
        operation="update",
        method="PUT",
        endpoint="/companies/{company_id}/departments/{department_id}",
        description="Update a company department. Use this to change fields on an existing company. Only the fields you supply are modified.\n\nWraps: PUT /companies/{company_id}/departments/{department_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="department_id",
                annotation=int | str,
                description="Department ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="name",
                annotation=str | None,
                description="Updated name",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="description",
                annotation=str | None,
                description="Updated description",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="delete_company_department",
        resource="company",
        operation="delete",
        method="DELETE",
        endpoint="/companies/{company_id}/departments/{department_id}",
        description="Delete a company department. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /companies/{company_id}/departments/{department_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="department_id",
                annotation=int | str,
                description="Department ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_company_pipelines",
        resource="company",
        operation="list",
        method="GET",
        endpoint="/companies/{company_id}/pipelines",
        description="List all pipelines associated with a company. Use this to enumerate companies and obtain their ids.\n\nWraps: GET /companies/{company_id}/pipelines",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="pipelines",
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_company_tags",
        resource="company",
        operation="list",
        method="GET",
        endpoint="/companies/{company_id}/tags",
        description="List all tags applied to a company. Use this to enumerate companies and obtain their ids.\n\nWraps: GET /companies/{company_id}/tags",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="tags",
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="replace_company_tags",
        resource="company",
        operation="replace",
        method="POST",
        endpoint="/companies/{company_id}/tags",
        description="Replace all tags on a company (replaces existing tags). Replaces the entire existing set. Anything omitted is removed.\n\nWraps: POST /companies/{company_id}/tags",
        safety=Safety.BULK,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_ids",
                annotation=list[int],
                description="List of tag IDs to apply",
                location=ParamLocation.BODY,
                wire_name="tags",
                transform=Transform.WRAP_ID,
            ),
        ),
    ),
    ToolSpec(
        name="attach_company_tags",
        resource="company",
        operation="attach",
        method="PUT",
        endpoint="/companies/{company_id}/tags",
        description="Attach additional tags to a company (additive). Adds to the existing set rather than replacing it.\n\nWraps: PUT /companies/{company_id}/tags",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_ids",
                annotation=list[int],
                description="List of tag IDs to add",
                location=ParamLocation.BODY,
                wire_name="tags",
                transform=Transform.WRAP_ID,
            ),
        ),
    ),
    ToolSpec(
        name="delete_company_tag",
        resource="company",
        operation="delete",
        method="DELETE",
        endpoint="/companies/{company_id}/tags/{tag_id}",
        description="Remove a specific tag from a company. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /companies/{company_id}/tags/{tag_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_id",
                annotation=int | str,
                description="Tag ID to remove",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_company_phones",
        resource="company",
        operation="list",
        method="GET",
        endpoint="/companies/{company_id}/phones",
        description="List all phone numbers for a company. Use this to enumerate companies and obtain their ids.\n\nWraps: GET /companies/{company_id}/phones",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="phones",
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Results per page",
                location=ParamLocation.QUERY,
                default=25,
            ),
        ),
    ),
    ToolSpec(
        name="get_company_phone",
        resource="company",
        operation="get",
        method="GET",
        endpoint="/companies/{company_id}/phones/{phone_id}",
        description="Get a specific company phone. Use this when you already have a company id and need its detail.\n\nWraps: GET /companies/{company_id}/phones/{phone_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone_id",
                annotation=int | str,
                description="Phone ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="create_company_phone",
        resource="company",
        operation="create",
        method="POST",
        endpoint="/companies/{company_id}/phones",
        description="Add a phone number for a company. Use this to add a new company record.\n\nWraps: POST /companies/{company_id}/phones",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone",
                annotation=str,
                description="Phone number",
                location=ParamLocation.BODY,
            ),
            Param(
                name="phone_type",
                annotation=str,
                description="Type (work, mobile, etc.)",
                location=ParamLocation.BODY,
                default="work",
                wire_name="type",
            ),
        ),
    ),
    ToolSpec(
        name="update_company_phone",
        resource="company",
        operation="update",
        method="PUT",
        endpoint="/companies/{company_id}/phones/{phone_id}",
        description="Update a company phone number. Use this to change fields on an existing company. Only the fields you supply are modified.\n\nWraps: PUT /companies/{company_id}/phones/{phone_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone_id",
                annotation=int | str,
                description="Phone ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone",
                annotation=str | None,
                description="Updated phone number",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="phone_type",
                annotation=str | None,
                description="Updated type",
                location=ParamLocation.BODY,
                default=None,
                wire_name="type",
            ),
        ),
    ),
    ToolSpec(
        name="delete_company_phone",
        resource="company",
        operation="delete",
        method="DELETE",
        endpoint="/companies/{company_id}/phones/{phone_id}",
        description="Delete a company phone number. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /companies/{company_id}/phones/{phone_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone_id",
                annotation=int | str,
                description="Phone ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="get_company_custom_field",
        resource="company",
        operation="get",
        method="GET",
        endpoint="/companies/{company_id}/custom_fields/{field_id}",
        description="Get a specific custom field for a company. Use this when you already have a company id and need its detail.\n\nWraps: GET /companies/{company_id}/custom_fields/{field_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="field_id",
                annotation=int | str,
                description="Custom field ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="get_company_thumbnail",
        resource="company",
        operation="get",
        method="GET",
        endpoint="/companies/{company_id}/thumbnail",
        description="Get a company's thumbnail image. Use this when you already have a company id and need its detail.\n\nWraps: GET /companies/{company_id}/thumbnail",
        safety=Safety.READ,
        response=ResponseStrategy.BINARY,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="change_company_thumbnail",
        resource="company",
        operation="change",
        method="PUT",
        endpoint="/companies/{company_id}/thumbnail",
        description="Update a company's thumbnail image.\n\nWraps: PUT /companies/{company_id}/thumbnail",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="Company ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="image_data",
                annotation=str,
                description="Base64 encoded image data or image URL",
                location=ParamLocation.BODY,
                wire_name="image",
            ),
        ),
    ),
    ToolSpec(
        name="update_company_custom_field",
        resource="company",
        operation="update",
        method="PUT",
        endpoint="/companies/{company_id}/custom_fields/{field_id}",
        description=(
            "Set the value of one custom field on a company. Use "
            "get_company_custom_fields to discover which fields exist and their ids.\n\n"
            "Wraps: PUT /companies/{company_id}/custom_fields/{field_id}"
        ),
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="companies",
        params=(
            Param(
                name="company_id",
                annotation=int | str,
                description="The unique identifier of the company",
                location=ParamLocation.PATH,
            ),
            Param(
                name="field_id",
                annotation=int | str,
                description="The unique identifier of the custom field",
                location=ParamLocation.PATH,
            ),
            Param(
                name="value",
                annotation=Any,
                description="New value for the custom field",
                location=ParamLocation.BODY,
            ),
        ),
    ),
]
