"""Contacts tool specifications.

Generated from the pre-refactor hand-written toolsets, then reviewed. Edit this
file directly; it is the source of truth for these tools.
"""

from __future__ import annotations

from typing import Any  # noqa: F401  (used in parameter annotations)

from cats_mcp.registry.models import (
    Param,
    ParamLocation,
    ResponseStrategy,
    Safety,
    ToolSpec,
    Transform,  # noqa: F401  (used by some specs)
)

SPECS: list[ToolSpec] = [
    ToolSpec(
        name="list_contacts",
        resource="contact",
        operation="list",
        method="GET",
        endpoint="/contacts",
        description="List contacts with pagination (returns SUMMARY by default). Use get_contact(id) for full details of a specific contact. Use this to enumerate contacts and obtain their ids.\n\nWraps: GET /contacts",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="contacts",
        toolset="contacts",
        params=(
            Param(
                name="per_page",
                annotation=int,
                description="Number of contacts per page (default: 10, max: 100)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number for pagination (default: 1)",
                location=ParamLocation.QUERY,
                default=1,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include, or "all" for full response',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="get_contact",
        resource="contact",
        operation="get",
        method="GET",
        endpoint="/contacts/{contact_id}",
        description="Get detailed information about a specific contact. Use this when you already have a contact id and need its detail.\n\nWraps: GET /contacts/{contact_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Unique identifier for the contact",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="create_contact",
        resource="contact",
        operation="create",
        method="POST",
        endpoint="/contacts",
        description="Create a new contact record. Use this to add a new contact record.\n\nWraps: POST /contacts",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="first_name",
                annotation=str,
                description="Contact's first name (required)",
                location=ParamLocation.BODY,
            ),
            Param(
                name="last_name",
                annotation=str,
                description="Contact's last name (required)",
                location=ParamLocation.BODY,
            ),
            Param(
                name="email",
                annotation=str,
                description="Contact's email address (required)",
                location=ParamLocation.BODY,
            ),
            Param(
                name="company_id",
                annotation=int | None,
                description="Associated company ID",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="title",
                annotation=str | None,
                description="Job title",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="phone",
                annotation=str | None,
                description="Phone number",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="notes",
                annotation=str | None,
                description="Additional notes",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="update_contact",
        resource="contact",
        operation="update",
        method="PUT",
        endpoint="/contacts/{contact_id}",
        description="Update an existing contact record. Use this to change fields on an existing contact. Only the fields you supply are modified.\n\nWraps: PUT /contacts/{contact_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="ID of contact to update",
                location=ParamLocation.PATH,
            ),
            Param(
                name="first_name",
                annotation=str | None,
                description="Updated first name",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="last_name",
                annotation=str | None,
                description="Updated last name",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="email",
                annotation=str | None,
                description="Updated email address",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="company_id",
                annotation=int | None,
                description="Updated company association",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="title",
                annotation=str | None,
                description="Updated job title",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="phone",
                annotation=str | None,
                description="Updated phone number",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="notes",
                annotation=str | None,
                description="Updated notes",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="delete_contact",
        resource="contact",
        operation="delete",
        method="DELETE",
        endpoint="/contacts/{contact_id}",
        description="Delete a contact record (permanent). Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /contacts/{contact_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="ID of contact to delete",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="search_contacts",
        resource="contact",
        operation="search",
        method="GET",
        endpoint="/contacts/search",
        description="Search contacts by name, email, or other criteria (returns SUMMARY by default). Use get_contact(id) for full details. Use this for keyword searches across contacts.\n\nWraps: GET /contacts/search",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="contacts",
        toolset="contacts",
        params=(
            Param(
                name="query",
                annotation=str,
                description="Search query string",
                location=ParamLocation.QUERY,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 10)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include, or "all" for full response',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="filter_contacts",
        resource="contact",
        operation="filter",
        method="POST",
        endpoint="/contacts/search",
        description="Filter contacts using advanced criteria (returns SUMMARY by default). Use get_contact(id) for full details. Use this to match contacts on exact field values.\n\nWraps: POST /contacts/search",
        safety=Safety.WRITE,
        response=ResponseStrategy.SUMMARY,
        collection_key="contacts",
        toolset="contacts",
        params=(
            Param(
                name="filter_field",
                annotation=str,
                description='Field to filter on (e.g., "company_id", "title", "first_name")',
                location=ParamLocation.BODY,
                wire_name="field",
            ),
            Param(
                name="filter_type",
                annotation=str,
                description=(
                    "Filter operator. WARNING: 'contains' tokenizes the value and "
                    "matches ANY token, so contains='Logan Lake' also returns "
                    "Williams Lake, Slave Lake and Deer Lake, and contains='Cache "
                    "Creek' returns every Creek. For any multi-word value such as a "
                    "municipality, use 'exactly' and run one filter per value. "
                    "Options: 'contains' (reliable only for single words), "
                    "'exactly', 'is_empty', 'greater_than', 'less_than', 'between', "
                    "'geo_distance' (radius from a postal code - prefer this for "
                    "'near X' rather than listing towns)."
                ),
                location=ParamLocation.BODY,
                wire_name="filter",
            ),
            Param(
                name="filter_value",
                annotation=Any,
                description="Value to filter by",
                location=ParamLocation.BODY,
                wire_name="value",
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Results per page (default: 10)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number",
                location=ParamLocation.QUERY,
                default=1,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include, or "all" for full response',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="list_contact_activities",
        resource="contact",
        operation="list",
        method="GET",
        endpoint="/contacts/{contact_id}/activities",
        description="List all activities for a specific contact. Use this to enumerate contacts and obtain their ids.\n\nWraps: GET /contacts/{contact_id}/activities",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="activities",
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Results per page",
                location=ParamLocation.QUERY,
                default=25,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="create_contact_activity",
        resource="contact",
        operation="create",
        method="POST",
        endpoint="/contacts/{contact_id}/activities",
        description="Create an activity for a contact. Use this to add a new contact record.\n\nWraps: POST /contacts/{contact_id}/activities",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="activity_type",
                annotation=str,
                description="Type (email, meeting, call_talked, call_lvm, call_missed, text_message, other)",
                location=ParamLocation.BODY,
                wire_name="type",
            ),
            Param(
                name="description",
                annotation=str,
                description="Activity description",
                location=ParamLocation.BODY,
            ),
            Param(
                name="notes",
                annotation=str | None,
                description="Additional notes",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="list_contact_attachments",
        resource="contact",
        operation="list",
        method="GET",
        endpoint="/contacts/{contact_id}/attachments",
        description="List all attachments for a contact. Use this to enumerate contacts and obtain their ids.\n\nWraps: GET /contacts/{contact_id}/attachments",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="attachments",
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Results per page",
                location=ParamLocation.QUERY,
                default=25,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="upload_contact_attachment",
        resource="contact",
        operation="upload",
        method="POST",
        endpoint="/contacts/{contact_id}/attachments",
        description="Upload an attachment to a contact. Use this to attach a file to the record.\n\nWraps: POST /contacts/{contact_id}/attachments",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="file_data",
                annotation=dict[str, Any],
                description="File upload data (multipart/form-data)",
                location=ParamLocation.BODY,
                transform=Transform.SPREAD,
            ),
        ),
    ),
    ToolSpec(
        name="get_contact_custom_fields",
        resource="contact",
        operation="get",
        method="GET",
        endpoint="/contacts/{contact_id}/custom_fields",
        description="Get custom fields for a contact. Use this when you already have a contact id and need its detail.\n\nWraps: GET /contacts/{contact_id}/custom_fields",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_contact_emails",
        resource="contact",
        operation="list",
        method="GET",
        endpoint="/contacts/{contact_id}/emails",
        description="List all email addresses for a contact. Use this to enumerate contacts and obtain their ids.\n\nWraps: GET /contacts/{contact_id}/emails",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="emails",
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Results per page",
                location=ParamLocation.QUERY,
                default=25,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="create_contact_email",
        resource="contact",
        operation="create",
        method="POST",
        endpoint="/contacts/{contact_id}/emails",
        description="Add an email address to a contact. Use this to add a new contact record.\n\nWraps: POST /contacts/{contact_id}/emails",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="email",
                annotation=str,
                description="Email address",
                location=ParamLocation.BODY,
            ),
            Param(
                name="email_type",
                annotation=str,
                description="Type (work, personal, other)",
                location=ParamLocation.BODY,
                default="work",
                wire_name="type",
            ),
        ),
    ),
    ToolSpec(
        name="update_contact_email",
        resource="contact",
        operation="update",
        method="PUT",
        endpoint="/contacts/{contact_id}/emails/{email_id}",
        description="Update a contact's email address. Use this to change fields on an existing contact. Only the fields you supply are modified.\n\nWraps: PUT /contacts/{contact_id}/emails/{email_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="email_id",
                annotation=int | str,
                description="Email record ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="email",
                annotation=str,
                description="Updated email address",
                location=ParamLocation.BODY,
            ),
            Param(
                name="email_type",
                annotation=str,
                description="Updated type (work, personal, other)",
                location=ParamLocation.BODY,
                wire_name="type",
            ),
        ),
    ),
    ToolSpec(
        name="delete_contact_email",
        resource="contact",
        operation="delete",
        method="DELETE",
        endpoint="/contacts/{contact_id}/emails/{email_id}",
        description="Delete a contact's email address. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /contacts/{contact_id}/emails/{email_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="email_id",
                annotation=int | str,
                description="Email record ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_contact_phones",
        resource="contact",
        operation="list",
        method="GET",
        endpoint="/contacts/{contact_id}/phones",
        description="List all phone numbers for a contact. Use this to enumerate contacts and obtain their ids.\n\nWraps: GET /contacts/{contact_id}/phones",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="phones",
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Results per page",
                location=ParamLocation.QUERY,
                default=25,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="create_contact_phone",
        resource="contact",
        operation="create",
        method="POST",
        endpoint="/contacts/{contact_id}/phones",
        description="Add a phone number to a contact. Use this to add a new contact record.\n\nWraps: POST /contacts/{contact_id}/phones",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone",
                annotation=str,
                description="Phone number",
                location=ParamLocation.BODY,
            ),
            Param(
                name="phone_type",
                annotation=str,
                description="Type (work, mobile, home, other)",
                location=ParamLocation.BODY,
                default="work",
                wire_name="type",
            ),
        ),
    ),
    ToolSpec(
        name="update_contact_phone",
        resource="contact",
        operation="update",
        method="PUT",
        endpoint="/contacts/{contact_id}/phones/{phone_id}",
        description="Update a contact's phone number. Use this to change fields on an existing contact. Only the fields you supply are modified.\n\nWraps: PUT /contacts/{contact_id}/phones/{phone_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone_id",
                annotation=int | str,
                description="Phone record ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone",
                annotation=str,
                description="Updated phone number",
                location=ParamLocation.BODY,
            ),
            Param(
                name="phone_type",
                annotation=str,
                description="Updated type (work, mobile, home, other)",
                location=ParamLocation.BODY,
                wire_name="type",
            ),
        ),
    ),
    ToolSpec(
        name="delete_contact_phone",
        resource="contact",
        operation="delete",
        method="DELETE",
        endpoint="/contacts/{contact_id}/phones/{phone_id}",
        description="Delete a contact's phone number. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /contacts/{contact_id}/phones/{phone_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="phone_id",
                annotation=int | str,
                description="Phone record ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_contact_pipelines",
        resource="contact",
        operation="list",
        method="GET",
        endpoint="/contacts/{contact_id}/pipelines",
        description="List all pipelines associated with a contact. Use this to enumerate contacts and obtain their ids.\n\nWraps: GET /contacts/{contact_id}/pipelines",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="pipelines",
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_contact_tags",
        resource="contact",
        operation="list",
        method="GET",
        endpoint="/contacts/{contact_id}/tags",
        description="List all tags applied to a contact. Use this to enumerate contacts and obtain their ids.\n\nWraps: GET /contacts/{contact_id}/tags",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="tags",
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="replace_contact_tags",
        resource="contact",
        operation="replace",
        method="POST",
        endpoint="/contacts/{contact_id}/tags",
        description="Replace all tags on a contact (replaces existing tags). Replaces the entire existing set. Anything omitted is removed.\n\nWraps: POST /contacts/{contact_id}/tags",
        safety=Safety.BULK,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_ids",
                annotation=list[int],
                description="List of tag IDs to apply",
                location=ParamLocation.BODY,
                wire_name="tags",
                transform=Transform.WRAP_ID,
            ),
        ),
    ),
    ToolSpec(
        name="attach_contact_tags",
        resource="contact",
        operation="attach",
        method="PUT",
        endpoint="/contacts/{contact_id}/tags",
        description="Attach additional tags to a contact (additive). Adds to the existing set rather than replacing it.\n\nWraps: PUT /contacts/{contact_id}/tags",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_ids",
                annotation=list[int],
                description="List of tag IDs to add",
                location=ParamLocation.BODY,
                wire_name="tags",
                transform=Transform.WRAP_ID,
            ),
        ),
    ),
    ToolSpec(
        name="delete_contact_tag",
        resource="contact",
        operation="delete",
        method="DELETE",
        endpoint="/contacts/{contact_id}/tags/{tag_id}",
        description="Remove a specific tag from a contact. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /contacts/{contact_id}/tags/{tag_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_id",
                annotation=int | str,
                description="Tag ID to remove",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="get_contact_custom_field",
        resource="contact",
        operation="get",
        method="GET",
        endpoint="/contacts/{contact_id}/custom_fields/{field_id}",
        description="Get a specific custom field for a contact. Use this when you already have a contact id and need its detail.\n\nWraps: GET /contacts/{contact_id}/custom_fields/{field_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="field_id",
                annotation=int | str,
                description="Custom field ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="get_contact_thumbnail",
        resource="contact",
        operation="get",
        method="GET",
        endpoint="/contacts/{contact_id}/thumbnail",
        description="Get a contact's thumbnail image. Use this when you already have a contact id and need its detail.\n\nWraps: GET /contacts/{contact_id}/thumbnail",
        safety=Safety.READ,
        response=ResponseStrategy.BINARY,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="change_contact_thumbnail",
        resource="contact",
        operation="change",
        method="PUT",
        endpoint="/contacts/{contact_id}/thumbnail",
        description="Update a contact's thumbnail image.\n\nWraps: PUT /contacts/{contact_id}/thumbnail",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="Contact ID",
                location=ParamLocation.PATH,
            ),
            Param(
                name="image_data",
                annotation=str,
                description="Base64 encoded image data or image URL",
                location=ParamLocation.BODY,
                wire_name="image",
            ),
        ),
    ),
    ToolSpec(
        name="list_contact_tasks",
        resource="contact",
        operation="list",
        method="GET",
        endpoint="/contacts/{contact_id}/tasks",
        description=(
            "List the tasks and reminders attached to a contact. Use this to see "
            "outstanding follow-ups with a client contact.\n\n"
            "Wraps: GET /contacts/{contact_id}/tasks"
        ),
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="tasks",
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="The unique identifier of the contact",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="update_contact_custom_field",
        resource="contact",
        operation="update",
        method="PUT",
        endpoint="/contacts/{contact_id}/custom_fields/{field_id}",
        description=(
            "Set the value of one custom field on a contact. Use "
            "get_contact_custom_fields to discover which fields exist and their ids.\n\n"
            "Wraps: PUT /contacts/{contact_id}/custom_fields/{field_id}"
        ),
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="contacts",
        params=(
            Param(
                name="contact_id",
                annotation=int | str,
                description="The unique identifier of the contact",
                location=ParamLocation.PATH,
            ),
            Param(
                name="field_id",
                annotation=int | str,
                description="The unique identifier of the custom field",
                location=ParamLocation.PATH,
            ),
            Param(
                name="value",
                annotation=Any,
                description="New value for the custom field",
                location=ParamLocation.BODY,
            ),
        ),
    ),
]
