"""Jobs tool specifications.

Generated from the pre-refactor hand-written toolsets, then reviewed. Edit this
file directly; it is the source of truth for these tools.
"""

from __future__ import annotations

from typing import Any  # noqa: F401  (used in parameter annotations)

from cats_mcp.registry.models import (
    Param,
    ParamLocation,
    ResponseStrategy,
    Safety,
    ToolSpec,
    Transform,  # noqa: F401  (used by some specs)
)

SPECS: list[ToolSpec] = [
    ToolSpec(
        name="list_jobs",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs",
        description="List jobs with compact summaries. Use this to review current openings. Returns ids for fetching detail; filter or search when looking for something specific.\n\nWraps: GET /jobs",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="jobs",
        toolset="jobs",
        params=(
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 10, max: 100)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number to retrieve (default: 1)",
                location=ParamLocation.QUERY,
                default=1,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include, or "all" for full response',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="get_job",
        resource="job",
        operation="get",
        method="GET",
        endpoint="/jobs/{job_id}",
        description="Get detailed information about a specific job. Use this when you already have a job id and need its detail.\n\nWraps: GET /jobs/{job_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="create_job",
        resource="job",
        operation="create",
        method="POST",
        endpoint="/jobs",
        description="Create a new job posting. Use this to add a new job record.\n\nWraps: POST /jobs",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="title",
                annotation=str,
                description="Job title",
                location=ParamLocation.BODY,
            ),
            Param(
                name="description",
                annotation=str,
                description="Job description",
                location=ParamLocation.BODY,
            ),
            Param(
                name="department",
                annotation=str | None,
                description="Department name (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="location",
                annotation=str | None,
                description="Job location (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="employment_type",
                annotation=str,
                description="Type of employment (default: 'full-time')",
                location=ParamLocation.BODY,
                default="full-time",
            ),
            Param(
                name="salary_min",
                annotation=int | None,
                description="Minimum salary (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="salary_max",
                annotation=int | None,
                description="Maximum salary (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="update_job",
        resource="job",
        operation="update",
        method="PUT",
        endpoint="/jobs/{job_id}",
        description="Update an existing job posting. Use this to change fields on an existing job. Only the fields you supply are modified.\n\nWraps: PUT /jobs/{job_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="title",
                annotation=str | None,
                description="Updated job title (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="description",
                annotation=str | None,
                description="Updated job description (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="status",
                annotation=str | None,
                description="Updated job status (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
            Param(
                name="location",
                annotation=str | None,
                description="Updated job location (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="delete_job",
        resource="job",
        operation="delete",
        method="DELETE",
        endpoint="/jobs/{job_id}",
        description="Permanently delete a job posting. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /jobs/{job_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="search_jobs",
        resource="job",
        operation="search",
        method="GET",
        endpoint="/jobs/search",
        description="Find open jobs by free-text keyword across title, description and location. Use this to identify which roles are hiring or find a job to submit a candidate to.\n\nWraps: GET /jobs/search",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="jobs",
        toolset="jobs",
        params=(
            Param(
                name="query",
                annotation=str,
                description="Search query string",
                location=ParamLocation.QUERY,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 10)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include, or "all" for full response',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="filter_jobs",
        resource="job",
        operation="filter",
        method="POST",
        endpoint="/jobs/search",
        description="Filter jobs with advanced criteria (returns SUMMARY by default). Use get_job(id) for full details of a specific job. Use this to match jobs on exact field values.\n\nWraps: POST /jobs/search",
        safety=Safety.WRITE,
        response=ResponseStrategy.SUMMARY,
        collection_key="jobs",
        toolset="jobs",
        params=(
            Param(
                name="filter_field",
                annotation=str,
                description='Field to filter on (e.g., "status_id", "department", "location")',
                location=ParamLocation.BODY,
                wire_name="field",
            ),
            Param(
                name="filter_type",
                annotation=str,
                description='Filter operator ("contains", "exactly", "is_empty", "greater_than", "less_than", "between")',
                location=ParamLocation.BODY,
                wire_name="filter",
            ),
            Param(
                name="filter_value",
                annotation=Any,
                description="Value to filter by",
                location=ParamLocation.BODY,
                wire_name="value",
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 10)",
                location=ParamLocation.QUERY,
                default=10,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number to retrieve (default: 1)",
                location=ParamLocation.QUERY,
                default=1,
            ),
            Param(
                name="fields",
                annotation=str | None,
                description='Comma-separated fields to include, or "all" for full response',
                location=ParamLocation.SHAPING,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="list_job_pipelines",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs/{job_id}/pipelines",
        description="List the candidates currently in a job's pipeline, with each one's stage. Use this to review the shortlist for a role or see who is under consideration.\n\nWraps: GET /jobs/{job_id}/pipelines",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="pipelines",
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
        ),
    ),
    ToolSpec(
        name="list_job_attachments",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs/{job_id}/attachments",
        description="List all attachments for a job. Use this to enumerate jobs and obtain their ids.\n\nWraps: GET /jobs/{job_id}/attachments",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="attachments",
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
        ),
    ),
    ToolSpec(
        name="list_job_custom_fields",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs/{job_id}/custom_fields",
        description="Get all custom fields for a job. Use this to enumerate jobs and obtain their ids.\n\nWraps: GET /jobs/{job_id}/custom_fields",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="custom_fields",
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="get_job_custom_field",
        resource="job",
        operation="get",
        method="GET",
        endpoint="/jobs/{job_id}/custom_fields/{field_id}",
        description="Get a specific custom field for a job. Use this when you already have a job id and need its detail.\n\nWraps: GET /jobs/{job_id}/custom_fields/{field_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="field_id",
                annotation=int | str,
                description="The unique identifier of the custom field",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="update_job_custom_field",
        resource="job",
        operation="update",
        method="PUT",
        endpoint="/jobs/{job_id}/custom_fields/{field_id}",
        description="Update a specific custom field for a job. Use this to change fields on an existing job. Only the fields you supply are modified.\n\nWraps: PUT /jobs/{job_id}/custom_fields/{field_id}",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="field_id",
                annotation=int | str,
                description="The unique identifier of the custom field",
                location=ParamLocation.PATH,
            ),
            Param(
                name="value",
                annotation=Any,
                description="The new value for the custom field",
                location=ParamLocation.BODY,
            ),
        ),
    ),
    ToolSpec(
        name="list_job_statuses",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs/statuses",
        description="List all available job statuses. Use this to enumerate jobs and obtain their ids.\n\nWraps: GET /jobs/statuses",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="statuses",
        toolset="jobs",
    ),
    ToolSpec(
        name="get_job_status",
        resource="job",
        operation="get",
        method="GET",
        endpoint="/jobs/statuses/{status_id}",
        description="Get a job status definition by ID. Use this when you already have a job id and need its detail.\n\nWraps: GET /jobs/statuses/{status_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="jobs",
        params=(
            Param(
                name="status_id",
                annotation=int | str,
                description="The unique identifier of the job status definition",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="change_job_status",
        resource="job",
        operation="change",
        method="POST",
        endpoint="/jobs/{job_id}/status",
        description="Change the status of a job.\n\nWraps: POST /jobs/{job_id}/status",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="status_id",
                annotation=int | str,
                description="The new status ID",
                location=ParamLocation.BODY,
                transform=Transform.TO_INT,
            ),
            Param(
                name="reason",
                annotation=str | None,
                description="Optional reason for the status change",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="list_job_tags",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs/{job_id}/tags",
        description="List all tags assigned to a job. Use this to enumerate jobs and obtain their ids.\n\nWraps: GET /jobs/{job_id}/tags",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="tags",
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="attach_job_tags",
        resource="job",
        operation="attach",
        method="PUT",
        endpoint="/jobs/{job_id}/tags",
        description="Add tags to a job (keeps existing tags). Adds to the existing set rather than replacing it.\n\nWraps: PUT /jobs/{job_id}/tags",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_ids",
                annotation=list[int],
                description="List of tag IDs to add",
                location=ParamLocation.BODY,
                wire_name="tags",
                transform=Transform.WRAP_ID,
            ),
        ),
    ),
    ToolSpec(
        name="delete_job_tag",
        resource="job",
        operation="delete",
        method="DELETE",
        endpoint="/jobs/{job_id}/tags/{tag_id}",
        description="Remove a specific tag from a job. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /jobs/{job_id}/tags/{tag_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_id",
                annotation=int | str,
                description="The unique identifier of the tag to remove",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_job_tasks",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs/{job_id}/tasks",
        description="List all tasks associated with a job. Use this to enumerate jobs and obtain their ids.\n\nWraps: GET /jobs/{job_id}/tasks",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="tasks",
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
        ),
    ),
    ToolSpec(
        name="list_job_lists",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs/lists",
        description="List all job lists/collections. Use this to enumerate jobs and obtain their ids.\n\nWraps: GET /jobs/lists",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="lists",
        toolset="jobs",
        params=(
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number to retrieve (default: 1)",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="get_job_list",
        resource="job",
        operation="get",
        method="GET",
        endpoint="/jobs/lists/{list_id}",
        description="Get details of a specific job list. Use this when you already have a job id and need its detail.\n\nWraps: GET /jobs/lists/{list_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="jobs",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="create_job_list",
        resource="job",
        operation="create",
        method="POST",
        endpoint="/jobs/lists",
        description="Create a new job list/collection. Use this to add a new job record.\n\nWraps: POST /jobs/lists",
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        constant_body=(("type", "job"),),
        toolset="jobs",
        params=(
            Param(
                name="name",
                annotation=str,
                description="Name of the job list",
                location=ParamLocation.BODY,
            ),
            Param(
                name="description",
                annotation=str | None,
                description="Description of the list (optional)",
                location=ParamLocation.BODY,
                default=None,
            ),
        ),
    ),
    ToolSpec(
        name="delete_job_list",
        resource="job",
        operation="delete",
        method="DELETE",
        endpoint="/jobs/lists/{list_id}",
        description="Delete a job list. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /jobs/lists/{list_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_job_list_items",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs/lists/{list_id}/items",
        description="List all items in a specific job list. Use this to enumerate jobs and obtain their ids.\n\nWraps: GET /jobs/lists/{list_id}/items",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="items",
        toolset="jobs",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
        ),
    ),
    ToolSpec(
        name="get_job_list_item",
        resource="job",
        operation="get",
        method="GET",
        endpoint="/jobs/lists/{list_id}/items/{item_id}",
        description="Get a specific item from a job list. Use this when you already have a job id and need its detail.\n\nWraps: GET /jobs/lists/{list_id}/items/{item_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="jobs",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
            Param(
                name="item_id",
                annotation=int | str,
                description="The unique identifier of the list item",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="create_job_list_items",
        resource="job",
        operation="create",
        method="POST",
        endpoint="/jobs/lists/{list_id}/items",
        description="Add jobs to a job list. Use this to add a new job record.\n\nWraps: POST /jobs/lists/{list_id}/items",
        safety=Safety.BULK,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
            Param(
                name="job_ids",
                annotation=list[int],
                description="List of job IDs to add",
                location=ParamLocation.BODY,
                wire_name="items",
                transform=Transform.WRAP_JOB_ID,
            ),
        ),
    ),
    ToolSpec(
        name="delete_job_list_item",
        resource="job",
        operation="delete",
        method="DELETE",
        endpoint="/jobs/lists/{list_id}/items/{item_id}",
        description="Remove an item from a job list. Permanently removes this record. This cannot be undone.\n\nWraps: DELETE /jobs/lists/{list_id}/items/{item_id}",
        safety=Safety.DESTRUCTIVE,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="list_id",
                annotation=int | str,
                description="The unique identifier of the list",
                location=ParamLocation.PATH,
            ),
            Param(
                name="item_id",
                annotation=int | str,
                description="The unique identifier of the list item to remove",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_job_applications",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs/{job_id}/applications",
        description="List the applications submitted to a specific job - the people who applied. Use this to review previous applicants for a role, find prior candidates worth re-approaching for a similar opening, or check whether someone already applied.\n\nWraps: GET /jobs/{job_id}/applications",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="applications",
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="per_page",
                annotation=int,
                description="Number of results per page (default: 25)",
                location=ParamLocation.QUERY,
                default=25,
            ),
            Param(
                name="page",
                annotation=int,
                description="Page number to retrieve (default: 1)",
                location=ParamLocation.QUERY,
                default=1,
            ),
        ),
    ),
    ToolSpec(
        name="get_job_application",
        resource="job",
        operation="get",
        method="GET",
        endpoint="/jobs/applications/{application_id}",
        description="Retrieve one job application, including the answers the applicant submitted. Use this after finding an application id to review what a specific applicant said.\n\nWraps: GET /jobs/applications/{application_id}",
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="jobs",
        params=(
            Param(
                name="application_id",
                annotation=int | str,
                description="The unique identifier of the application",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_job_application_fields",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs/applications/{application_id}/fields",
        description="List all fields for a specific job application. Use this to enumerate jobs and obtain their ids.\n\nWraps: GET /jobs/applications/{application_id}/fields",
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="fields",
        toolset="jobs",
        params=(
            Param(
                name="application_id",
                annotation=int | str,
                description="The unique identifier of the application",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="list_job_custom_field_definitions",
        resource="job",
        operation="list",
        method="GET",
        endpoint="/jobs/custom_fields",
        description=(
            "List every job custom field configured on this CATS account, with its id, "
            "label and type. Call this first to discover which fields exist and their ids, "
            "since the tools that read or write a value require the field id and those ids "
            "differ per account.\n\nWraps: GET /jobs/custom_fields"
        ),
        safety=Safety.READ,
        response=ResponseStrategy.SUMMARY,
        collection_key="custom_fields",
        toolset="jobs",
        params=(),
    ),
    ToolSpec(
        name="get_job_custom_field_definition",
        resource="job",
        operation="get",
        method="GET",
        endpoint="/jobs/custom_fields/{field_id}",
        description=(
            "Retrieve the definition of one job custom field, including its type and any "
            "selectable options. Use this to find the valid values for a field before "
            "writing to it.\n\nWraps: GET /jobs/custom_fields/{field_id}"
        ),
        safety=Safety.READ,
        response=ResponseStrategy.DETAIL,
        toolset="jobs",
        params=(
            Param(
                name="field_id",
                annotation=int | str,
                description="The unique identifier of the custom field definition",
                location=ParamLocation.PATH,
            ),
        ),
    ),
    ToolSpec(
        name="upload_job_attachment",
        resource="job",
        operation="upload",
        method="POST",
        endpoint="/jobs/{job_id}/attachments",
        description=(
            "Attach a file to a job, such as a job description or client specification. "
            "Use list_job_attachments to see what is already attached.\n\n"
            "Wraps: POST /jobs/{job_id}/attachments"
        ),
        safety=Safety.WRITE,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="filename",
                annotation=str,
                description="Filename to store the attachment under",
                location=ParamLocation.QUERY,
            ),
            Param(
                name="file_data",
                annotation=dict[str, Any],
                description="Attachment payload as required by the CATS attachments API",
                location=ParamLocation.BODY,
                transform=Transform.SPREAD,
            ),
        ),
    ),
    ToolSpec(
        name="replace_job_tags",
        resource="job",
        operation="replace",
        method="POST",
        endpoint="/jobs/{job_id}/tags",
        description=(
            "Replace all of a job's tags with a new set. This removes any tag not in the "
            "list. Prefer attach_job_tags unless deliberately resetting categorisation.\n\n"
            "Wraps: POST /jobs/{job_id}/tags"
        ),
        safety=Safety.BULK,
        response=ResponseStrategy.RAW,
        toolset="jobs",
        params=(
            Param(
                name="job_id",
                annotation=int | str,
                description="The unique identifier of the job",
                location=ParamLocation.PATH,
            ),
            Param(
                name="tag_ids",
                annotation=list[int],
                description="Complete list of tag IDs the job should have after this call",
                location=ParamLocation.BODY,
                wire_name="tags",
                transform=Transform.WRAP_ID,
            ),
        ),
    ),
]
