#!/usr/bin/env python
"""Generate the tool-coverage tables from the registry.

The audit found five different hand-maintained tool counts across README,
server logs, tests and design documents - four of them wrong. Counts are now
generated from the single source of truth, and `tests/test_docs_drift.py`
fails if the generated block and the committed file diverge.

    python scripts/generate_tool_docs.py           # print
    python scripts/generate_tool_docs.py --write   # update docs/TOOLS.md
"""

from __future__ import annotations

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))

from cats_mcp.registry.catalog import REGISTRY  # noqa: E402
from cats_mcp.registry.models import Safety  # noqa: E402

OUTPUT = pathlib.Path("docs/TOOLS.md")

#: Composite tools live outside the endpoint registry, plus the status tool.
COMPOSITE_COUNT = 5
STATUS_TOOL_COUNT = 1

#: The other two MCP primitives. Asserted against the running server in
#: tests/test_docs_drift.py, so these cannot quietly go stale either.
RESOURCE_COUNT = 5
TEMPLATE_COUNT = 1
PROMPT_COUNT = 5


def render() -> str:
    counts = REGISTRY.counts()
    total_endpoint_tools = len(REGISTRY)
    grand_total = total_endpoint_tools + COMPOSITE_COUNT + STATUS_TOOL_COUNT

    by_safety: dict[str, int] = {}
    for spec in REGISTRY:
        by_safety[spec.safety.value] = by_safety.get(spec.safety.value, 0) + 1

    lines: list[str] = []
    add = lines.append

    add("<!-- GENERATED by scripts/generate_tool_docs.py - do not edit by hand -->")
    add("")
    add("# Tool Coverage")
    add("")
    add(f"**{grand_total} tools total**: {total_endpoint_tools} CATS endpoint tools, ")
    add(f"{COMPOSITE_COUNT} composite read primitives, and {STATUS_TOOL_COUNT} status tool.")
    add("")
    add(f"Plus {RESOURCE_COUNT} resources, {TEMPLATE_COUNT} resource template and ")
    add(f"{PROMPT_COUNT} prompts - see below.")
    add("")
    add("## By toolset")
    add("")
    add("Select with `CATS_TOOLSETS=candidates,jobs` or `CATS_TOOLSETS=all`.")
    add("")
    add("| Toolset | Tools |")
    add("| --- | ---: |")
    for name, count in counts.items():
        add(f"| `{name}` | {count} |")
    add(f"| **total** | **{total_endpoint_tools}** |")
    add("")
    add("## By safety class")
    add("")
    add("Drives MCP annotations and the scope required to discover or call a tool.")
    add("")
    add("| Safety | Tools | Scope |")
    add("| --- | ---: | --- |")
    for safety in Safety:
        count = by_safety.get(safety.value, 0)
        if count:
            add(f"| `{safety.value}` | {count} | `{safety.required_scope}` |")
    add("")
    add("## Composite read primitives")
    add("")
    add("Not one-to-one with CATS endpoints. Each answers a question that would")
    add("otherwise cost several round trips, and returns a compact table rather than")
    add("full records. Data access only - they report facts, never decisions.")
    add("")
    add("| Tool | Purpose |")
    add("| --- | --- |")
    add("| `get_candidate_summaries` | compact profiles for a batch of candidate ids |")
    add("| `get_candidate_engagement` | last contact date and activity counts for a batch |")
    add("| `get_job_candidate_pool` | a job's pipeline joined to candidate profiles |")
    add("| `get_changed_records` | what changed since an event id or timestamp |")
    add("| `get_pipeline_summaries` | status for a batch of pipeline ids |")
    add("")
    add("## Resources")
    add("")
    add("Read-only context, lazy-loaded. Resources are data a client reads; tools")
    add("are actions a model invokes. The first three work with CATS unreachable.")
    add("")
    add("| URI | Purpose |")
    add("| --- | --- |")
    add("| `cats://server/capabilities` | what this adapter owns, does not own, "
        "and how it is configured |")
    add("| `cats://server/tools` | catalog shape by toolset and safety class |")
    add("| `cats://account/rate-limit` | live request budget |")
    add("| `cats://account/site` | which CATS account is connected |")
    add("| `cats://reference/workflows` | account-specific pipeline stages and "
        "their status ids |")
    add("| `cats://reference/custom-fields/{resource}` | custom field definitions and ids |")
    add("")
    add("## Prompts")
    add("")
    add("Guidance on operating the CATS API correctly - resolving account-specific")
    add("ids, staying inside the request budget. Deliberately nothing about who to")
    add("contact or how to rank anyone; `tests/test_prompts.py` enforces that.")
    add("")
    add("| Prompt | Prevents |")
    add("| --- | --- |")
    add("| `change_pipeline_stage_safely` | a valid-but-wrong status id silently moving a record |")
    add("| `search_within_rate_budget` | a lookup loop exhausting the hourly limit |")
    add("| `find_the_right_custom_field` | guessing account-specific custom field ids |")
    add("| `record_an_external_interaction` | assuming this server sends email or "
        "SMS - it does not |")
    add("")
    add("## Endpoint coverage")
    add("")
    add("| Method | Endpoints |")
    add("| --- | ---: |")
    methods: dict[str, int] = {}
    for spec in REGISTRY:
        methods[spec.method.upper()] = methods.get(spec.method.upper(), 0) + 1
    for method in ("GET", "POST", "PUT", "DELETE"):
        if method in methods:
            add(f"| `{method}` | {methods[method]} |")
    add("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write docs/TOOLS.md")
    parser.add_argument("--check", action="store_true", help="exit 1 if docs are stale")
    args = parser.parse_args()

    content = render()

    if args.check:
        if not OUTPUT.exists():
            print(f"{OUTPUT} does not exist; run with --write", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT} is out of date; run: python {__file__} --write", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is up to date")
        return 0

    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"wrote {OUTPUT}")
        return 0

    print(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
